[package]
name = "graft-core"
version = "0.2.0"
edition = "2024"

[dependencies]
bsdiff = "0.2.1"
flate2 = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"
tar = "0.4"

[dev-dependencies]
tempfile = "3.24"
